
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Alignment alignment3;
	
	private global::Gtk.VBox vbox2;
	
	private global::Gtk.HBox hbox1;
	
	private global::Gtk.TextView textview2;
	
	private global::Gtk.Entry num1;
	
	private global::Gtk.HBox hbox2;
	
	private global::Gtk.TextView textview3;
	
	private global::Gtk.ComboBox combobox1;
	
	private global::Gtk.HBox hbox3;
	
	private global::Gtk.TextView textview1;
	
	private global::Gtk.ComboBox combobox2;
	
	private global::Gtk.HBox hbox4;
	
	private global::Gtk.Button button1;
	
	private global::Gtk.VBox vbox3;
	
	private global::Gtk.ScrolledWindow GtkScrolledWindow;
	
	private global::Gtk.TextView textview4;
	
	private global::Gtk.Statusbar statusbar1;
	
	private global::Gtk.Button button2;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.WidthRequest = 500;
		this.HeightRequest = 500;
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("Conversor de Bases\n");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.BorderWidth = ((uint)(15));
		this.Resizable = false;
		this.AllowGrow = false;
		this.DefaultWidth = 500;
		this.DefaultHeight = 500;
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.alignment3 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
		this.alignment3.Name = "alignment3";
		// Container child alignment3.Gtk.Container+ContainerChild
		this.vbox2 = new global::Gtk.VBox ();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox ();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.textview2 = new global::Gtk.TextView ();
		this.textview2.Buffer.Text = "Digite aqui o numero que deseja converter.";
		this.textview2.Sensitive = false;
		this.textview2.CanFocus = true;
		this.textview2.Name = "textview2";
		this.textview2.Editable = false;
		this.textview2.CursorVisible = false;
		this.textview2.AcceptsTab = false;
		this.textview2.WrapMode = ((global::Gtk.WrapMode)(2));
		this.textview2.PixelsAboveLines = 5;
		this.hbox1.Add (this.textview2);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.textview2]));
		w1.Position = 0;
		// Container child hbox1.Gtk.Box+BoxChild
		this.num1 = new global::Gtk.Entry ();
		global::Gtk.Tooltips w2 = new Gtk.Tooltips ();
		w2.SetTip (this.num1, "Digite o numero para conversao.", "Digite o numero para conversao.");
		this.num1.WidthRequest = 145;
		this.num1.CanFocus = true;
		this.num1.Name = "num1";
		this.num1.IsEditable = true;
		this.num1.MaxLength = 200;
		this.num1.InvisibleChar = '●';
		this.hbox1.Add (this.num1);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.num1]));
		w3.Position = 1;
		this.vbox2.Add (this.hbox1);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox1]));
		w4.Position = 0;
		w4.Expand = false;
		w4.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox ();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.textview3 = new global::Gtk.TextView ();
		this.textview3.Buffer.Text = "Informe a base de origem do numero.";
		this.textview3.Sensitive = false;
		this.textview3.CanFocus = true;
		this.textview3.Name = "textview3";
		this.textview3.Editable = false;
		this.textview3.CursorVisible = false;
		this.textview3.AcceptsTab = false;
		this.textview3.WrapMode = ((global::Gtk.WrapMode)(3));
		this.textview3.PixelsAboveLines = 6;
		this.hbox2.Add (this.textview3);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.textview3]));
		w5.Position = 0;
		// Container child hbox2.Gtk.Box+BoxChild
		this.combobox1 = global::Gtk.ComboBox.NewText ();
		this.combobox1.AppendText (global::Mono.Unix.Catalog.GetString ("Base de origem"));
		this.combobox1.AppendText (global::Mono.Unix.Catalog.GetString ("Binario"));
		this.combobox1.AppendText (global::Mono.Unix.Catalog.GetString ("Octal"));
		this.combobox1.AppendText (global::Mono.Unix.Catalog.GetString ("Decimal"));
		this.combobox1.AppendText (global::Mono.Unix.Catalog.GetString ("Hexadecimal"));
		w2.SetTip (this.combobox1, "Base de Origem", "Base de Origem");
		this.combobox1.WidthRequest = 181;
		this.combobox1.Name = "combobox1";
		this.combobox1.Active = 0;
		this.hbox2.Add (this.combobox1);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.combobox1]));
		w6.Position = 1;
		w6.Expand = false;
		w6.Fill = false;
		this.vbox2.Add (this.hbox2);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox2]));
		w7.Position = 1;
		w7.Expand = false;
		w7.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox3 = new global::Gtk.HBox ();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.textview1 = new global::Gtk.TextView ();
		this.textview1.Buffer.Text = "Informe a base de destino do numero";
		this.textview1.Sensitive = false;
		this.textview1.CanFocus = true;
		this.textview1.Name = "textview1";
		this.textview1.Editable = false;
		this.textview1.CursorVisible = false;
		this.textview1.AcceptsTab = false;
		this.textview1.WrapMode = ((global::Gtk.WrapMode)(3));
		this.textview1.PixelsAboveLines = 6;
		this.hbox3.Add (this.textview1);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.textview1]));
		w8.Position = 0;
		// Container child hbox3.Gtk.Box+BoxChild
		this.combobox2 = global::Gtk.ComboBox.NewText ();
		this.combobox2.AppendText (global::Mono.Unix.Catalog.GetString ("Base de destino"));
		this.combobox2.AppendText (global::Mono.Unix.Catalog.GetString ("Binario"));
		this.combobox2.AppendText (global::Mono.Unix.Catalog.GetString ("Octal"));
		this.combobox2.AppendText (global::Mono.Unix.Catalog.GetString ("Decimal"));
		this.combobox2.AppendText (global::Mono.Unix.Catalog.GetString ("Hexadecimal"));
		this.combobox2.WidthRequest = 181;
		this.combobox2.Name = "combobox2";
		this.combobox2.Active = 0;
		this.hbox3.Add (this.combobox2);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.combobox2]));
		w9.Position = 1;
		w9.Expand = false;
		w9.Fill = false;
		this.vbox2.Add (this.hbox3);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox3]));
		w10.Position = 2;
		w10.Expand = false;
		w10.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox4 = new global::Gtk.HBox ();
		this.hbox4.Name = "hbox4";
		this.hbox4.Spacing = 6;
		// Container child hbox4.Gtk.Box+BoxChild
		this.button1 = new global::Gtk.Button ();
		this.button1.CanFocus = true;
		this.button1.Name = "button1";
		this.button1.UseUnderline = true;
		this.button1.Label = global::Mono.Unix.Catalog.GetString ("Converter");
		this.hbox4.Add (this.button1);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.button1]));
		w11.Position = 0;
		this.vbox2.Add (this.hbox4);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox4]));
		w12.Position = 3;
		w12.Expand = false;
		w12.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.vbox3 = new global::Gtk.VBox ();
		this.vbox3.WidthRequest = 500;
		this.vbox3.HeightRequest = 200;
		this.vbox3.Name = "vbox3";
		this.vbox3.Spacing = 6;
		// Container child vbox3.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		this.GtkScrolledWindow.WindowPlacement = ((global::Gtk.CornerType)(3));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.textview4 = new global::Gtk.TextView ();
		this.textview4.WidthRequest = 500;
		this.textview4.HeightRequest = 200;
		this.textview4.CanFocus = true;
		this.textview4.Name = "textview4";
		this.textview4.WrapMode = ((global::Gtk.WrapMode)(3));
		this.GtkScrolledWindow.Add (this.textview4);
		this.vbox3.Add (this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.GtkScrolledWindow]));
		w14.Position = 0;
		this.vbox2.Add (this.vbox3);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.vbox3]));
		w15.Position = 4;
		w15.Expand = false;
		w15.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.statusbar1 = new global::Gtk.Statusbar ();
		this.statusbar1.Name = "statusbar1";
		this.statusbar1.Spacing = 6;
		// Container child statusbar1.Gtk.Box+BoxChild
		this.button2 = new global::Gtk.Button ();
		this.button2.CanFocus = true;
		this.button2.Name = "button2";
		this.button2.UseUnderline = true;
		this.button2.Label = global::Mono.Unix.Catalog.GetString ("Sobre");
		this.statusbar1.Add (this.button2);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.statusbar1 [this.button2]));
		w16.Position = 2;
		w16.Expand = false;
		w16.Fill = false;
		this.vbox2.Add (this.statusbar1);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.statusbar1]));
		w17.PackType = ((global::Gtk.PackType)(1));
		w17.Position = 5;
		w17.Expand = false;
		w17.Fill = false;
		this.alignment3.Add (this.vbox2);
		this.Add (this.alignment3);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.num1.Changed += new global::System.EventHandler (this.OnNum1Changed);
		this.button1.Clicked += new global::System.EventHandler (this.OnButton1Clicked);
		this.button2.Clicked += new global::System.EventHandler (this.OnButton2Clicked);
	}
}
